// Datos de los cardenales con sus rangos de fechas e imágenes
const cardinals = [
    { start: '01-01', end: '03-01', name: 'Cardenal Mario Grech', image: 'public/images/cardenal-mario-grech.jpg' },
    { start: '04-01', end: '06-01', name: 'Cardenal Leonardo Ulrich Steiner', image: 'public/images/Cardenal Leonardo Ulrich Steiner.jpeg' },
    { start: '07-01', end: '09-01', name: 'Cardenal Carlos Aguiar Retes', image: 'public/images/Cardenal Carlos Aguiar Retes.jpeg' },
    { start: '10-01', end: '12-01', name: 'Cardenal Jean-Claude Hollerich', image: 'public/images/cardenal-jean-claude-hollerich.jpg' },
    { start: '13-01', end: '15-01', name: 'Cardenal Soane Patita Mafi', image: 'public/images/Cardenal Soane Patita Mafi.jpeg' },
    { start: '16-01', end: '18-01', name: 'Cardenal Matteo Zuppi', image: 'public/images/cardenal-matteo-zuppi.jpg' },
    { start: '19-01', end: '21-01', name: 'Cardenal Luis Antonio Tagle', image: 'public/images/cardenal-luis-antonio-tagle.jpg' },
    { start: '22-01', end: '24-01', name: 'Cardenal Lazzaro You Heung-sik', image: 'public/images/Cardenal Lazzaro You Heung-sik.jpeg' },
    { start: '25-01', end: '27-01', name: 'Cardenal Wilton Gregory', image: 'public/images/cardenal-wilton-gregory.jpg' },
    { start: '28-01', end: '30-01', name: 'Cardenal Dieudonné Nzapalainga', image: 'public/images/cardenal-dieudonne-nzapalainga.jpg' },
    { start: '31-01', end: '02-02', name: 'Cardenal Víctor Manuel Fernández', image: 'public/images/cardenal-victor-manuel-fernandez.jpg' },
    { start: '03-02', end: '05-02', name: 'Cardenal Konrad Krajewski', image: 'public/images/Cardenal Konrad Krajewski.jpeg' },
    { start: '06-02', end: '08-02', name: 'Cardenal Antoine Kambanda', image: 'public/images/Cardenal Antoine Kambanda.jpeg' },
    { start: '09-02', end: '11-02', name: 'Cardenal Robert Prevost', image: 'public/images/cardenal-robert-prevost.jpg' },
    { start: '12-02', end: '14-02', name: 'Cardenal Juan José Omella', image: 'public/images/Cardenal Juan José Omella.jpeg' },
    { start: '15-02', end: '17-02', name: 'Cardenal Gérald C. Lacroix', image: 'public/images/Cardenal Gérald C. Lacroix.jpeg' },
    { start: '18-02', end: '20-02', name: 'Cardenal Cristóbal López Romero', image: 'public/images/Cardenal Cristóbal López Romero.jpeg' },
    { start: '21-02', end: '23-02', name: 'Cardenal Fridolin Ambongo Besungu', image: 'public/images/Cardenal Fridolin Ambongo Besungu.jpeg' },
    { start: '24-02', end: '26-02', name: 'Cardenal Stephen Ameyu Martin', image: 'public/images/Cardenal Stephen Ameyu Martin.jpeg' },
    { start: '27-02', end: '29-02', name: 'Cardenal José Cobo Cano', image: 'public/images/Cardenal José Cobo Cano.jpeg' },
    { start: '01-03', end: '03-03', name: 'Cardenal Paulo Cezar Costa', image: 'public/images/Cardenal Paulo Cezar Costa.jpeg' },
    { start: '04-03', end: '06-03', name: 'Cardenal Angelo De Donatis', image: 'public/images/cardenal-angelo-de-donatis.jpg' },
    { start: '07-03', end: '09-03', name: 'Cardenal Arthur Roche', image: 'public/images/Cardenal Arthur Roche.jpeg' },
    { start: '10-03', end: '12-03', name: 'Cardenal Américo Aguiar', image: 'public/images/Cardenal Américo Aguiar.jpeg' },
    { start: '13-03', end: '15-03', name: 'Cardenal Celestino Aós Braco', image: 'public/images/Cardenal Celestino Aós Braco.jpeg' },
    { start: '16-03', end: '18-03', name: 'Cardenal José Tolentino Mendonça', image: 'public/images/Cardenal José Tolentino Mendonça.jpeg' },
    { start: '19-03', end: '21-03', name: 'Cardenal Kevin Farrell', image: 'public/images/cardenal-kevin-farrell.jpg' },
    { start: '22-03', end: '24-03', name: 'Cardenal Christophe Pierre', image: 'public/images/Cardenal Christophe Pierre.jpeg' },
    { start: '25-03', end: '27-03', name: 'Cardenal Odilo Pedro Scherer', image: 'public/images/Cardenal Odilo Pedro Scherer.jpeg' },
    { start: '28-03', end: '30-03', name: 'Cardenal Leonardo Sandri', image: 'public/images/cardenal-leonardo-sandri.jpg' },
    { start: '31-03', end: '02-04', name: 'Cardenal Mauro Gambetti', image: 'public/images/Cardenal Mauro Gambetti.jpeg' },
    { start: '03-04', end: '05-04', name: 'Cardenal Patrick D\'Rozario', image: 'public/images/Cardenal Patrick De virRozario.jpeg' },
    { start: '06-04', end: '08-04', name: 'Cardenal Jean-Marc Aveline', image: 'public/images/Cardenal Jean-Marc Aveline.jpeg' },
    { start: '09-04', end: '11-04', name: 'Cardenal Pierbattista Pizzaballa', image: 'public/images/Cardenal Pierbattista Pizzaballa.jpeg' },
    { start: '12-04', end: '14-04', name: 'Cardenal Baltazar Porras', image: 'public/images/Cardenal Baltazar Porras.jpeg' },
    { start: '15-04', end: '17-04', name: 'Cardenal José Luis Lacunza', image: 'public/images/Cardenal José Luis Lacunza.jpeg' },
    { start: '18-04', end: '20-04', name: 'Cardenal Rubén Salazar Gómez', image: 'public/images/Cardenal Rubén Salazar Gómez.jpeg' },
    { start: '21-04', end: '23-04', name: 'Cardenal Rainer Maria Woelki', image: 'public/images/Cardenal Rainer Maria Woelki.jpeg' },
    { start: '24-04', end: '26-04', name: 'Cardenal Luis José Rueda Aparicio', image: 'public/images/Cardenal Luis José Rueda Aparicio.jpeg' },
    { start: '27-04', end: '29-04', name: 'Cardenal Paolo Lojudice', image: 'public/images/Cardenal Paolo Lojudice.jpeg' },
    { start: '30-04', end: '02-05', name: 'Cardenal Andrew Yeom Soo-jung', image: 'public/images/Cardenal Andrew Yeom Soo-jung.jpeg' },
    { start: '03-05', end: '05-05', name: 'Cardenal Telesphore P. Toppo', image: 'public/images/Cardenal Telesphore P. Toppo.jpeg' },
    { start: '06-05', end: '08-05', name: 'Cardenal Fernando Vérgez Alzaga', image: 'public/images/Cardenal Fernando Vérgez Alzaga.jpeg' },
    { start: '09-05', end: '11-05', name: 'Cardenal Mario Grech', image: 'public/images/cardenal-mario-grech.jpg' },
    { start: '12-05', end: '14-05', name: 'Cardenal A. Agostino Vallini', image: 'public/images/Cardenal A. Agostino Vallini.jpeg' },
    { start: '15-05', end: '17-05', name: 'Cardenal Raniero Cantalamessa', image: 'public/images/Cardenal Raniero Cantalamessa.jpeg' },
    { start: '18-05', end: '20-05', name: 'Cardenal Thomas Collins', image: 'public/images/Cardenal Thomas Collins.jpeg' },
    { start: '21-05', end: '23-05', name: 'Cardenal Albert Malcolm Ranjith', image: 'public/images/cardenal-albert-malcolm-ranjith.jpg' },
    { start: '24-05', end: '26-05', name: 'Cardenal Beniamino Stella', image: 'public/images/Cardenal Beniamino Stella.jpeg' },
    { start: '27-05', end: '29-05', name: 'Cardenal Michael Czerny', image: 'public/images/Cardenal Michael Czerny.jpeg' },
    { start: '30-05', end: '01-06', name: 'Cardenal Seán Patrick O\'Malley', image: 'public/images/cardenal-sean-patrick-omalley.jpg' },
    { start: '02-06', end: '04-06', name: 'Cardenal José Advincula', image: 'public/images/Cardenal José Advincula.jpeg' },
    { start: '05-06', end: '07-06', name: 'Cardenal Daniel DiNardo', image: 'public/images/cardenal-daniel-dinardo.jpg' },
    { start: '08-06', end: '10-06', name: 'Cardenal Gérard Cyprien Lacroix', image: 'public/images/Cardenal Gérard Cyprien Lacroix.jpeg' },
    { start: '11-06', end: '13-06', name: 'Cardenal Christophe Pierre', image: 'public/images/Cardenal Christophe Pierre.jpeg' },
    { start: '14-06', end: '16-06', name: 'Cardenal Blase Cupich', image: 'public/images/cardenal-blase-cupich.jpg' },
    { start: '17-06', end: '19-06', name: 'Cardenal Óscar Andrés Rodríguez Maradiaga', image: 'public/images/cardenal-oscar-rodriguez-maradiaga.jpg' },
    { start: '20-06', end: '22-06', name: 'Cardenal Joseph W. Tobin', image: 'public/images/Cardenal Joseph W. Tobin.jpeg' },
    { start: '23-06', end: '25-06', name: 'Cardenal Timothy Dolan', image: 'public/images/cardenal-timothy-dolan.jpg' },
    { start: '26-06', end: '28-06', name: 'Cardenal Joseph Coutts', image: 'public/images/cardenal-joseph-coutts.jpg' },
    { start: '29-06', end: '01-07', name: 'Cardenal Luis Francisco Ladaria', image: 'public/images/Cardenal Luis Francisco Ladaria.jpeg' },
    { start: '02-07', end: '04-07', name: 'Cardenal Gualtiero Bassetti', image: 'public/images/Cardenal Gualtiero Bassetti.jpeg' },
    { start: '05-07', end: '07-07', name: 'Cardenal Gregorio Rosa Chávez', image: 'public/images/Cardenal Gregorio Rosa Chávez.jpeg' },
    { start: '08-07', end: '10-07', name: 'Cardenal Francisco Montenegro', image: 'public/images/Cardenal Francisco Montenegro.jpeg' },
    { start: '11-07', end: '13-07', name: 'Cardenal Jorge Urosa Savino', image: 'public/images/Cardenal Jorge Urosa Savino.jpeg' },
    { start: '14-07', end: '16-07', name: 'Cardenal Angelo Bagnasco', image: 'public/images/Cardenal Angelo Bagnasco.jpeg' },
    { start: '17-07', end: '19-07', name: 'Cardenal Zenon Grocholewski', image: 'public/images/Cardenal Zenon Grocholewski.jpeg' },
    { start: '20-07', end: '22-07', name: 'Cardenal Gregorio Rosa Chávez', image: 'public/images/Cardenal Gregorio Rosa Chávez.jpeg' },
    { start: '23-07', end: '25-07', name: 'Cardenal Ángel Sixto Rossi', image: 'public/images/Cardenal Ángel Sixto Rossi.jpeg' },
    { start: '26-07', end: '28-07', name: 'Cardenal Ángel Fernández Artime', image: 'public/images/Cardenal Ángel Fernández Artime.jpeg' },
    { start: '29-07', end: '31-07', name: 'Cardenal Claudio Gugerotti', image: 'public/images/Cardenal Claudio Gugerotti.jpeg' },
    { start: '01-08', end: '03-08', name: 'Cardenal Víctor Manuel Fernández', image: 'public/images/cardenal-victor-manuel-fernandez.jpg' },
    { start: '04-08', end: '06-08', name: 'Cardenal Thomas Aquinas Manyo', image: 'public/images/Cardenal Thomas Aquinas Manyo.jpeg' },
    { start: '07-08', end: '09-08', name: 'Cardenal Giorgio Marengo', image: 'public/images/Cardenal Giorgio Marengo.jpeg' },
    { start: '10-08', end: '12-08', name: 'Cardenal Paul Richard Gallagher', image: 'public/images/Cardenal Paul Richard Gallagher.jpeg' },
    { start: '13-08', end: '15-08', name: 'Cardenal Leopoldo José Brenes', image: 'public/images/Cardenal Leopoldo José Brenes.jpeg' },
    { start: '16-08', end: '18-08', name: 'Cardenal Adalberto Martínez', image: 'public/images/Cardenal Adalberto Martínez.jpeg' },
    { start: '19-08', end: '21-08', name: 'Cardenal Anthony Poola', image: 'public/images/Cardenal Anthony Poola.jpeg' },
    { start: '22-08', end: '24-08', name: 'Cardenal Richard Baawobr', image: 'public/images/Cardenal Richard Baawobr.jpeg' },
    { start: '25-08', end: '27-08', name: 'Cardenal Virgílio do Carmo da Silva', image: 'public/images/Cardenal Virgílio do Carmo da Silva.jpeg' },
    { start: '28-08', end: '30-08', name: 'Cardenal Stephen Chow', image: 'public/images/Cardenal Stephen Chow.jpeg' },
    { start: '31-08', end: '02-09', name: 'Cardenal Emil Paul Tscherrig', image: 'public/images/Cardenal Emil Paul Tscherrig.jpeg' },
    { start: '03-09', end: '05-09', name: 'Cardenal Emiliano Tardif', image: 'public/images/Cardenal Emiliano Tardif.jpeg' },
    { start: '06-09', end: '08-09', name: 'Cardenal Jean-Pierre Kutwa', image: 'public/images/Cardenal Jean-Pierre Kutwa.jpeg' },
    { start: '09-09', end: '11-09', name: 'Cardenal Pedro Barreto', image: 'public/images/cardenal-pedro-barreto.jpg' },
    { start: '12-09', end: '14-09', name: 'Cardenal Augustin Hollerich', image: 'public/images/Cardenal Augustin Hollerich.jpeg' },
    { start: '15-09', end: '17-09', name: 'Cardenal Maurice Piat', image: 'public/images/Cardenal Maurice Piat.jpeg' },
    { start: '18-09', end: '20-09', name: 'Cardenal José Cobo Cano', image: 'public/images/Cardenal José Cobo Cano.jpeg' },
    { start: '21-09', end: '23-09', name: 'Cardenal Angelus Sepe', image: 'public/images/Cardenal Angelus Sepe.jpeg' },
    { start: '24-09', end: '26-09', name: 'Cardenal José Cobo Cano', image: 'public/images/Cardenal José Cobo Cano.jpeg' },
    { start: '27-09', end: '29-09', name: 'Cardenal Carlos Castillo Mattasoglio', image: 'public/images/Cardenal Carlos Castillo Mattasoglio.jpeg' },
    { start: '30-09', end: '02-10', name: 'Cardenal Cristóbal López Romero', image: 'public/images/Cardenal Cristóbal López Romero.jpeg' },
    { start: '03-10', end: '05-10', name: 'Cardenal Leonardo Ulrich Steiner', image: 'public/images/Cardenal Leonardo Ulrich Steiner.jpeg' },
    { start: '06-10', end: '08-10', name: 'Cardenal Antoine Kambanda', image: 'public/images/Cardenal Antoine Kambanda.jpeg' },
    { start: '09-10', end: '11-10', name: 'Cardenal Luis José Rueda Aparicio', image: 'public/images/Cardenal Luis José Rueda Aparicio.jpeg' },
    { start: '12-10', end: '14-10', name: 'Cardenal Mario Grech', image: 'public/images/cardenal-mario-grech.jpg' },
    { start: '15-10', end: '17-10', name: 'Cardenal Ángel Fernández Artime', image: 'public/images/Cardenal Ángel Fernández Artime.jpeg' },
    { start: '18-10', end: '20-10', name: 'Cardenal Robert McElroy', image: 'public/images/Cardenal Robert McElroy.jpeg' },
    { start: '21-10', end: '23-10', name: 'Cardenal Filipe Neri Ferrão', image: 'public/images/Cardenal Filipe Neri Ferrão.jpeg' },
    { start: '24-10', end: '26-10', name: 'Cardenal José Francisco Robles', image: 'public/images/Cardenal José Francisco Robles.jpeg' },
    { start: '27-10', end: '29-10', name: 'Cardenal Dominik Duka', image: 'public/images/Cardenal Dominik Duka.jpeg' },
    { start: '30-10', end: '01-11', name: 'Cardenal Silvano Tomasi', image: 'public/images/Cardenal Silvano Tomasi.jpeg' },
    { start: '02-11', end: '04-11', name: 'Cardenal Daniel Sturla', image: 'public/images/Cardenal Daniel Sturla.jpeg' },
    { start: '05-11', end: '07-11', name: 'Cardenal Jorge Eduardo Lozano', image: 'public/images/Cardenal Jorge Eduardo Lozano.jpeg' },
    { start: '08-11', end: '10-11', name: 'Cardenal Álvaro Ramazzini', image: 'public/images/Cardenal Álvaro Ramazzini.jpeg' },
    { start: '11-11', end: '13-11', name: 'Cardenal Ángel Sixto Rossi', image: 'public/images/Cardenal Ángel Sixto Rossi.jpeg' },
    { start: '14-11', end: '16-11', name: 'Cardenal Cristián Roncagliolo', image: 'public/images/Cardenal Cristián Roncagliolo.jpeg' },
    { start: '17-11', end: '19-11', name: 'Cardenal José Cobo Cano', image: 'public/images/Cardenal José Cobo Cano.jpeg' },
    { start: '20-11', end: '22-11', name: 'Cardenal Américo Aguiar', image: 'public/images/Cardenal Américo Aguiar.jpeg' },
    { start: '23-11', end: '25-11', name: 'Cardenal Luis Antonio Tagle', image: 'public/images/cardenal-luis-antonio-tagle.jpg' },
    { start: '26-11', end: '28-11', name: 'Cardenal Jean-Marc Aveline', image: 'public/images/Cardenal Jean-Marc Aveline.jpeg' },
    { start: '29-11', end: '01-12', name: 'Cardenal Pierbattista Pizzaballa', image: 'public/images/Cardenal Pierbattista Pizzaballa.jpeg' },
    { start: '02-12', end: '04-12', name: 'Cardenal Claudio Gugerotti', image: 'public/images/Cardenal Claudio Gugerotti.jpeg' },
    { start: '05-12', end: '07-12', name: 'Cardenal Víctor Manuel Fernández', image: 'public/images/cardenal-victor-manuel-fernandez.jpg' },
    { start: '08-12', end: '10-12', name: 'Cardenal Paul Gallagher', image: 'public/images/Cardenal Paul Gallagher.jpeg' },
    { start: '11-12', end: '13-12', name: 'Cardenal Christophe Pierre', image: 'public/images/Cardenal Christophe Pierre.jpeg' },
    { start: '14-12', end: '16-12', name: 'Cardenal José Tolentino Mendonça', image: 'public/images/Cardenal José Tolentino Mendonça.jpeg' },
    { start: '17-12', end: '19-12', name: 'Cardenal Lazzaro You', image: 'public/images/Cardenal Lazzaro You Heung-sik.jpeg' },
    { start: '20-12', end: '22-12', name: 'Cardenal Arthur Roche', image: 'public/images/Cardenal Arthur Roche.jpeg' },
    { start: '23-12', end: '25-12', name: 'Cardenal Jean-Claude Hollerich', image: 'public/images/cardenal-jean-claude-hollerich.jpg' },
    { start: '26-12', end: '28-12', name: 'Cardenal Mario Grech', image: 'public/images/cardenal-mario-grech.jpg' },
    { start: '29-12', end: '31-12', name: 'Cardenal Matteo Zuppi', image: 'public/images/cardenal-matteo-zuppi.jpg' }
];

// Exportar los datos para que sean accesibles desde otros archivos
export default cardinals;